export const GET_DATA = "GET_DATA";
export const DATA_PER_COMPANY = "DATA_PER_COMPANY";
export const FILTER_COMPANIES = "FILTER_COMPANIES";
export const FILTER_COMPANIES_DETAIL= "FILTER_COMPANIES_DETAIL";
export const CLEAR_STATE = "CLEAR_STATE";